spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6" # cron scheduled for each Saturday at noon (12:00)
    facade:
      count: 6
      lower-band: 1
      upper-band: 99
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connection-timeout: 5000
          read-timeout: 5000